/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projek;
import java.sql.*;
import javax.swing.table.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.*;



/**
 *
 * @author Waldetrudis Anut
 */
public class Catatan extends javax.swing.JFrame {


    /**
     * Creates new form Apk
     */
    public Catatan() {
         initComponents();
    setLocationRelativeTo(null); // <--- Tengah layar

    // Tambahkan komponen manual yang tidak dibuat lewat GUI Builder
    no.setVisible(false);
    id_catatan.setVisible(false);
    getContentPane().add(no);
    getContentPane().add(id_catatan);

    no.setEnabled(false);
    id_catatan.setEnabled(false);
    tampil_data();

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int baris = jTable1.getSelectedRow();
                if (baris != -1) {
                    no.setText(jTable1.getValueAt(baris, 1).toString());  // ← Ambil no_db tersembunyi
                    id_catatan.setText(jTable1.getValueAt(baris, 2).toString());
                    try {
                        java.util.Date tanggal = new SimpleDateFormat("yyyy-MM-dd").parse(jTable1.getValueAt(baris, 3).toString());
                        tgl.setDate(tanggal);
                    } catch (Exception e) {
                        e.printStackTrace();
                        tgl.setDate(null);
                    }
                    isi.setText(jTable1.getValueAt(baris, 4).toString());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        isi = new javax.swing.JTextField();
        tb_hapus = new javax.swing.JButton();
        tb_simpan = new javax.swing.JButton();
        tb_edit = new javax.swing.JButton();
        tgl = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tb_lihat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("Catatan Harian Sederhana");

        jLabel4.setText("tanggal");

        jLabel5.setText("isi_catatan");

        isi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiActionPerformed(evt);
            }
        });

        tb_hapus.setText("Hapus");
        tb_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_hapusActionPerformed(evt);
            }
        });

        tb_simpan.setText("Tambah");
        tb_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_simpanActionPerformed(evt);
            }
        });

        tb_edit.setText("Edit");
        tb_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_editActionPerformed(evt);
            }
        });

        tgl.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglPropertyChange(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "no", "id_catatan", "tanggal", "isi_catatan"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        tb_lihat.setText("Lihat");
        tb_lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_lihatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(isi, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tb_lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb_simpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb_edit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb_hapus)))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(isi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tb_lihat)
                            .addComponent(tb_simpan)
                            .addComponent(tb_edit)
                            .addComponent(tb_hapus)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(280, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public class LihatIsi extends javax.swing.JFrame {

    public LihatIsi(String isiCatatan) {
            initComponents();
            area_isi.setText(isiCatatan);
        }

        private void initComponents() {
            JScrollPane scrollPane = new JScrollPane();
            area_isi = new JTextArea();
            setTitle("Lihat Isi Catatan");

            area_isi.setColumns(30);
            area_isi.setRows(15);
            area_isi.setLineWrap(true);
            area_isi.setWrapStyleWord(true);
            area_isi.setEditable(false);

            scrollPane.setViewportView(area_isi);

            getContentPane().add(scrollPane);
            pack();
            setLocationRelativeTo(null); // Tengah layar
        }

        private JTextArea area_isi;
    }


    private void tb_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_editActionPerformed
        try {
        String tanggal = new SimpleDateFormat("yyyy-MM-dd").format(tgl.getDate());
        String sql = "UPDATE tbcatatan SET id_catatan=?, tgl=?, isi_catatan=? WHERE no=?";
        Connection conn = projek.Koneksi.koneksiDB();
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, id_catatan.getText());
        pst.setString(2, tanggal);
        pst.setString(3, isi.getText());
        pst.setString(4, no.getText());

        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data berhasil diubah");
        tampil_data();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal mengubah data");
        e.printStackTrace();  // Lihat error jelas di console
    }
    }//GEN-LAST:event_tb_editActionPerformed

    private void tglPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglPropertyChange
if (tgl.getDate() != null) {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = format.format(tgl.getDate());
        // jika mau dipakai nanti, bisa disimpan di variabel global
    }
    }//GEN-LAST:event_tglPropertyChange


    private void tb_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_simpanActionPerformed
    try {
        if (tgl.getDate() == null || isi.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tanggal dan isi catatan tidak boleh kosong!");
            return;
        }

        String tanggal = new SimpleDateFormat("yyyy-MM-dd").format(tgl.getDate());

Connection conn = projek.Koneksi.koneksiDB();

// Hitung jumlah data sebelumnya
String countSql = "SELECT COUNT(*) AS total FROM tbcatatan";
PreparedStatement countPst = conn.prepareStatement(countSql);
ResultSet countRs = countPst.executeQuery();
int nomor = 1;
if (countRs.next()) {
    nomor = countRs.getInt("total") + 1;
}

String idBaru = generateIdCatatan(nomor);

String insertSql = "INSERT INTO tbcatatan (no, id_catatan, tgl, isi_catatan) VALUES (?, ?, ?, ?)";
PreparedStatement pst = conn.prepareStatement(insertSql);
pst.setInt(1, nomor);
pst.setString(2, idBaru);
pst.setString(3, tanggal);
pst.setString(4, isi.getText());
pst.executeUpdate();


        JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
        no.setText("");
        id_catatan.setText("");
        isi.setText("");
        tgl.setDate(null);
        tampil_data();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal menambahkan data: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_tb_simpanActionPerformed

    private void isiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiActionPerformed

    private void tb_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_hapusActionPerformed
int confirm = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            Connection conn = projek.Koneksi.koneksiDB();
            String sql = "DELETE FROM tbcatatan WHERE no=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, no.getText());
            int deleted = pst.executeUpdate();

            if (deleted > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                no.setText("");
                id_catatan.setText("");
                isi.setText("");
                tgl.setDate(null);
                tampil_data();
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menghapus data: " + e.getMessage());
            e.printStackTrace();
        }
        perbaruiUrutanSetelahHapus();

    }
    
    }//GEN-LAST:event_tb_hapusActionPerformed

    private void tb_lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_lihatActionPerformed
        int baris = jTable1.getSelectedRow();
        if (baris != -1) {
            String isiCatatan = jTable1.getValueAt(baris, 4).toString(); // ← Kolom ke-4 = ISI CATATAN
            LihatIsi lihat = new LihatIsi(isiCatatan);
            lihat.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Silakan pilih data terlebih dahulu di tabel.");
        }
    }//GEN-LAST:event_tb_lihatActionPerformed
     public void tampil_data(){
         DefaultTableModel tabel = new DefaultTableModel();
    tabel.addColumn("No");
    tabel.addColumn("No_id");
    tabel.addColumn("Id Catatan");
    tabel.addColumn("Tanggal");
    tabel.addColumn("Isi Catatan");

    try {
        Connection conn = projek.Koneksi.koneksiDB();
        String sql = "SELECT * FROM tbcatatan ORDER BY no ASC";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        int nomor = 1;
        while (rs.next()) {
            tabel.addRow(new Object[]{
                nomor++,
                rs.getString("no"),
                rs.getString("id_catatan"),
                rs.getString("tgl"),
                rs.getString("isi_catatan")
            });
        }
        jTable1.setModel(tabel);

        // Sembunyikan kolom no_db (opsional)
        jTable1.getColumnModel().getColumn(1).setMinWidth(0);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(1).setWidth(0);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
    }
}
    private String generateIdCatatan(int nomor) {
    return String.format("CT%03d", nomor);
}
    
private void perbaruiUrutanSetelahHapus() {
    try {
        Connection conn = projek.Koneksi.koneksiDB();

        String selectSql = "SELECT * FROM tbcatatan ORDER BY no ASC";
        PreparedStatement selectPst = conn.prepareStatement(selectSql);
        ResultSet rs = selectPst.executeQuery();

        int nomorBaru = 1;
        while (rs.next()) {
            int noLama = rs.getInt("no");
            String idBaru = generateIdCatatan(nomorBaru);

            String updateSql = "UPDATE tbcatatan SET no=?, id_catatan=? WHERE no=?";
            PreparedStatement updatePst = conn.prepareStatement(updateSql);
            updatePst.setInt(1, nomorBaru);
            updatePst.setString(2, idBaru);
            updatePst.setInt(3, noLama);
            updatePst.executeUpdate();

            nomorBaru++;
        }

        tampil_data(); // Refresh tabel setelah reindex

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memperbarui urutan: " + e.getMessage());
        e.printStackTrace();
    }
}


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catatan().setVisible(true);
            }
        });
    }
    
    private javax.swing.JTextField no = new JTextField();      // Menyimpan kolom no (hidden)
    private javax.swing.JTextField id_catatan = new JTextField(); // Menyimpan ID catatan (readonly)
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField isi;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton tb_edit;
    private javax.swing.JButton tb_hapus;
    private javax.swing.JButton tb_lihat;
    private javax.swing.JButton tb_simpan;
    private com.toedter.calendar.JDateChooser tgl;
    // End of variables declaration//GEN-END:variables

}
